title: 'CARIC: Cooperative Aerial Robots Inspection Challenge'
description: A Multi-UAV Benchmark for Aerial Robot Inspection Schemes
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker